curl -v http://localhost:8080/api/user/me ^
   -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NTMzMTcxOTEsImV4cCI6MTc1MzMyMDc5MX0.Cz1MPDBrTKjxJcKIp-7NDx_4v8Uuystw9PzuVX6xl0I"

@echo off
rem invalid_token  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.blahtellmewhycarisInFrontyardXNlciIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NTMyOTk0MzEsImV4cCI6MTc1MzMwMzAzMX0.zLDaZDnSgCgXwGrufD17Tmnw2tjU4AmsWy0hP3gCqSI"

rem   -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NTMyOTk0MzEsImV4cCI6MTc1MzMwMzAzMX0.zLDaZDnSgCgXwGrufD17Tmnw2tjU4AmsWy0hP3gCqSI"
